    [default_config]
    assembler = "nasm"
    instruction_set = "x86"

    [default_config.opts]
    compiler = "nasm"
    compile_flags_txt = ["-f elf32"]
    diagnostics = true
    default_diagnostics = true
